### ISSUE TITLE
Unable to play audio through bluetooth

### ISSUE THREAD

**Issue by gladykov** [Magisk-Modules-Alt-Repo/audio-samplerate-changer#1]
Zenfone 9 + Android 14 + Module version 1.1.1

Same device as in https://github.com/yzyhk904/audio-samplerate-changer/issues/2

====

After connecting to bluetooth speaker, audio cotninues to be played by phone speaker. Manually selecting bluetooth speaker as audio output, does not change audio output. 

Speaker: JBL Charge 3

**Comment by gladykov** [comment]
Let me know if I can provide more logs

**Comment by yzyhk904** [comment]
I guess your phone cannot run the AOSP bluetooth HAL, but can a bluetooth offloading driver and perhaps the QTI bluetooth HAL. This module doesn't support the offloading driver (having worse audio quality).

The AOSP bluetooth HAL occasionally doesn't work on some ROMs (almost on stock ones), but the QTI HAL may work instead. Try this testing module [magisk-module-audio-samplerate-changer-testing.zip](https://github.com/user-attachments/files/18075317/magisk-module-audio-samplerate-changer-testing.zip).

If this module works, attach here the output of a command execution `getprop ro.product.board`. I will add a code changing to bluetooth_qti for your device in the next release version.

**Comment by gladykov** [comment]
Nice man, thank you again! It worked.

`ro.product.board` = `taro`

**Comment by yzyhk904** [comment]
I've released v1.1.2 fixing your issue.

**Comment by gladykov** [comment]
@yzyhk904 Released version is not working. I looked on the commit. Is this space expected there:

https://github.com/Magisk-Modules-Alt-Repo/audio-samplerate-changer/commit/a57df2f29095d4df936deb336a51539c91b7714f#diff-a0ca0a221fd6474e97228cb64f05ea0dd039f9babe802109336e0524d7571680R84

Also I have `/vendor/lib64/hw/audio.bluetooth_qti.default.so` on my FS so this is not the case

**Comment by yzyhk904** [comment]
Sorry, it's a typo. I fixed it and replaced the latest release ZIP file

**Comment by gladykov** [comment]
Thank you! I confirm it works in latest release

**Comment by yzyhk904** [comment]
Thanks for your confirmation.
